# Caddy route for project: ${project_name}
# Generated by platform-infra Terraform

${project_name}-api.${domain} {
    reverse_proxy ${project_name}-api:${api_port}
}

${project_name}.${domain} {
    reverse_proxy ${project_name}-web:80
}

${project_name}-admin.${domain} {
    reverse_proxy ${project_name}-admin:80
}
